package vista;
import javax.swing.*;

public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("VerduleríaCR - Sistema de Facturación");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProductos = new javax.swing.JButton();
        btnNuevaFactura = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iproducto.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(this::btnProductosActionPerformed);
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 120, 70));

        btnNuevaFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ifactura.png"))); // NOI18N
        btnNuevaFactura.setText("Nueva Factura");
        btnNuevaFactura.addActionListener(this::btnNuevaFacturaActionPerformed);
        getContentPane().add(btnNuevaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 140, 70));

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iclientes.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);
        getContentPane().add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 120, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frutas.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -220, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        new GestionProductosForm().setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaFacturaActionPerformed
      new NuevaFacturaForm().setVisible(true);
    }//GEN-LAST:event_btnNuevaFacturaActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        new GestionClientesForm().setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnNuevaFactura;
    private javax.swing.JButton btnProductos;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
